#!/usr/bin/env python3
"""Generate migration/queue.md: realm-core translation units ordered leaves-first.

Depth is computed over #include edges *within* upstream/src/realm/ only; standard
library and external includes are depth 0. Leaves come first because a unit whose
dependencies are still C++ can only be ported behind a shim, and shims are the thing
the boundary count is meant to keep down.

Run from the repo root: python3 migration/gen_queue.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "upstream" / "src" / "realm"
INCLUDE = re.compile(rb'^\s*#\s*include\s*[<"]([^">]+)[">]', re.M)

# Subtrees that are not core storage and should not lead the queue.
SKIP = ("object-store/", "sync/", "parser/", "exec/", "tools/", "metrics/")


def rel(p: Path) -> str:
    return str(p.relative_to(ROOT))


def main() -> int:
    if not SRC.is_dir():
        print("upstream/src/realm not found — run: git submodule update --init --recursive",
              file=sys.stderr)
        return 2

    sources = [p for p in SRC.rglob("*.cpp")
               if not any(s in str(p.relative_to(SRC)) for s in SKIP)]

    # unit key -> path stem, so array.cpp and array.hpp are one unit
    units: dict[str, dict] = {}
    for cpp in sources:
        key = str(cpp.relative_to(SRC).with_suffix(""))
        hpp = cpp.with_suffix(".hpp")
        text = cpp.read_bytes() + (hpp.read_bytes() if hpp.exists() else b"")
        deps = set()
        for inc in INCLUDE.findall(text):
            i = inc.decode("utf8", "replace")
            if i.startswith("realm/"):
                d = i[len("realm/"):]
                d = re.sub(r"\.(hpp|h)$", "", d)
                if d != key:
                    deps.add(d)
        units[key] = {
            "cpp": rel(cpp),
            "lines": len(cpp.read_bytes().splitlines()),
            "deps": deps,
        }

    # Depth = longest chain of intra-realm deps. Cycles are real in this codebase,
    # so cap the recursion and mark anything that hits the cap.
    memo: dict[str, int] = {}

    def depth(k: str, seen: frozenset[str]) -> int:
        if k in memo:
            return memo[k]
        if k in seen or k not in units:
            return 0
        d = 1 + max((depth(x, seen | {k}) for x in units[k]["deps"] if x in units), default=-1)
        memo[k] = d
        return d

    for k in units:
        units[k]["depth"] = depth(k, frozenset())

    inbound = {k: 0 for k in units}
    for k, u in units.items():
        for d in u["deps"]:
            if d in inbound:
                inbound[d] += 1

    order = sorted(units.items(), key=lambda kv: (kv[1]["depth"], kv[1]["lines"], kv[0]))
    total = len(order)
    shown = order[:60]

    out = [
        "# Port queue",
        "",
        f"Generated by `migration/gen_queue.py` from realm-core at "
        f"`upstream/src/realm/`. {total} translation units total; the first 60 are listed.",
        "",
        "Ordered leaves-first by dependency depth, then by size. Depth counts only",
        "`#include`s within `upstream/src/realm/`; external and stdlib includes are 0.",
        "Depth 0 means the unit pulls in nothing else from realm — those are the only",
        "units that can be ported without a shim, and they are where to start.",
        "",
        "`inbound` is how many other units depend on this one. High inbound at low depth",
        "means porting it unblocks a lot; it is also the highest-risk place to get an",
        "element-width decision wrong, because everything downstream inherits it.",
        "",
        "Do not hand-edit this file — regenerate it. Record progress in JOURNAL.md.",
        "",
        "| # | unit | depth | inbound | lines |",
        "|---|---|---|---|---|",
    ]
    for i, (k, u) in enumerate(shown, 1):
        out.append(f"| {i} | `{u['cpp']}` | {u['depth']} | {inbound[k]} | {u['lines']} |")

    d0 = sum(1 for _, u in order if u["depth"] == 0)
    out += [
        "",
        f"Depth-0 (shim-free) units available: **{d0}** of {total}.",
        "",
        "If that number is small, the port will be shim-heavy from the start and the",
        "boundary count in `make shim-report` will rise before it falls. That is expected;",
        "what is not expected is it continuing to rise across two reflection passes.",
    ]
    (ROOT / "migration" / "queue.md").write_text("\n".join(out) + "\n")
    print(f"wrote migration/queue.md — {total} units, {d0} at depth 0")
    return 0


if __name__ == "__main__":
    sys.exit(main())
